### ISSUE TITLE
Unable to download package via NPM

### ISSUE THREAD

**Issue by cjativa** [samvera/node-iiif#26]
Hi! I am looking to use this project package for some IIIF tiling I am aiming to do using NodeJS.

However, I can't get the package to download from NPM. It perhaps might be an NPM issue, but I've tried a few different NodeJS environments and the install gets stuck at this step

```
npm install --save iiif-processor
[..................] | fetchMetadata: sill resolveWithNewModule iiif-processor@3.1.2
```

Is anyone able to reproduce this as well? Thank you!

**Comment by mbklein** [comment]
I've been unable to reproduce this. I'm assuming it was a temporary npm outage or network issue.
